version: '3.7'

services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myinvest
      - POSTGRES_PASSWORD=myinvest
      - POSTGRES_DB=myinvest

